project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://h9-sonic.github.io/H9Sonic.github.io/ # you must change this appropriately for RSS feeds to work properly
  title: "Daniel Vargas"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css



